/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package henry.savaryjackson.javatetrisproject.GUI;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import henry.savaryjackson.javatetrisproject.utils.WebUtils.APIUtils;
import javax.swing.JOptionPane;
import org.springframework.web.reactive.function.client.WebClientRequestException;
import org.springframework.web.reactive.function.client.WebClientResponseException;

/**
 *
 * @author hsavaryjackson
 */
public class UserDetails extends javax.swing.JFrame {

    /**
     * Creates new form UserDetails
     */
    private JsonObject userData;
    private int highScore;
    private String username;

    public UserDetails(JsonObject userData) {
	
	this.userData = userData;

	initComponents();

	updateUI();

    }
    
    private void updateUI(){
	if (userData.has("high_score")) {
	    highScore = userData.getAsJsonPrimitive("high_score").getAsInt();
	    lblHighScore.setText("High Score: " + String.valueOf(highScore));
	}
	if (userData.has("username")) {
	    username = userData.getAsJsonPrimitive("username").getAsString();
	    lblUsername.setText("Username: " + username);
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChangeUsername = new javax.swing.JButton();
        btnDeleteAccount = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblHighScore = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnChangeUsername.setFont(new java.awt.Font("Futura", 1, 20)); // NOI18N
        btnChangeUsername.setText("Change Username");
        btnChangeUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeUsernameActionPerformed(evt);
            }
        });

        btnDeleteAccount.setFont(new java.awt.Font("Futura", 1, 20)); // NOI18N
        btnDeleteAccount.setText("Delete Account");
        btnDeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAccountActionPerformed(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Futura", 1, 20)); // NOI18N
        lblUsername.setText("Username:");

        lblHighScore.setFont(new java.awt.Font("Futura", 1, 20)); // NOI18N
        lblHighScore.setText("High Score:");

        btnBack.setFont(new java.awt.Font("Futura", 1, 20)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnChangePassword.setFont(new java.awt.Font("Futura", 1, 20)); // NOI18N
        btnChangePassword.setText("Change Password");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnBack)
                .addContainerGap(324, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnDeleteAccount)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChangePassword)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(226, 226, 226))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblUsername)
                                .addComponent(lblHighScore))
                            .addGap(122, 122, 122))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnChangeUsername)
                            .addGap(78, 78, 78)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnBack)
                .addGap(15, 15, 15)
                .addComponent(lblUsername)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblHighScore)
                .addGap(29, 29, 29)
                .addComponent(btnChangeUsername)
                .addGap(18, 18, 18)
                .addComponent(btnChangePassword)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteAccount)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeUsernameActionPerformed
	// TODO add your handling code here:
	String newUsername;

	while (true) {
	    newUsername = JOptionPane.showInputDialog(this, "Please enter your new username");

	    if (newUsername == null) {
		return;
	    }

	    if (newUsername.equals("")) {
		JOptionPane.showMessageDialog(this, "Please enter a username", "Error", JOptionPane.ERROR_MESSAGE);
		continue;
	    }

	    try {
		
		APIUtils.changeUsername(ApplicationContext.getToken(), newUsername);
		
	    } catch (NullPointerException | WebClientRequestException ex) {
		
		JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		continue;
		
	    } catch (WebClientResponseException ex) {
		
		JsonObject body = (JsonObject) JsonParser.parseString(ex.getResponseBodyAsString());
		if (body == null) {
		    JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		    continue;
		}
		if (body.has("Status")) {
		    String status = body.getAsJsonPrimitive("Status").getAsString();
		    JOptionPane.showMessageDialog(this, status, "Error", JOptionPane.ERROR_MESSAGE);
		    if (status.equals("Invalid Token")) {
			ApplicationContext.disposeUserDetailsScreen();
			ApplicationContext.getLoginScreen().setVisible(true);
			return;
		    }
		} else {
		    JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

		}
		continue;

	    }
	    break;
	}
	// update ui
	userData.addProperty("username", newUsername);
	updateUI();

    }//GEN-LAST:event_btnChangeUsernameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
	// TODO add your handling code here:
	ApplicationContext.disposeUserDetailsScreen();
	ApplicationContext.getMainScreen().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAccountActionPerformed
	// TODO add your handling code here:
	if ((JOptionPane.showConfirmDialog(this, "Are you sure you want to delete your account", "Deleting your account",
		JOptionPane.YES_NO_CANCEL_OPTION) == JOptionPane.OK_OPTION)) {

	    try {
		APIUtils.deleteUser(ApplicationContext.getToken());
	    } catch (NullPointerException | WebClientRequestException ex) {
		
		JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		
	    } catch (WebClientResponseException ex) {
		JsonObject body = (JsonObject) JsonParser.parseString(ex.getResponseBodyAsString());
		if (body == null) {
		    JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		    return;
		}
		if (body.has("Status")) {
		    String status = body.getAsJsonPrimitive("Status").getAsString();
		    JOptionPane.showMessageDialog(this, status, "Error", JOptionPane.ERROR_MESSAGE);
		} else {
		    JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

		}

	    } finally {
		ApplicationContext.disposeUserDetailsScreen();
		ApplicationContext.getLoginScreen().setVisible(true);
	    }

	}


    }//GEN-LAST:event_btnDeleteAccountActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
	//
	String oldPassword = JOptionPane.showInputDialog(this, "Please enter your old password");
	
	
	if (oldPassword == null) {
		return;
	}

	if (oldPassword.equals("")) {
	    JOptionPane.showMessageDialog(this, "Please enter a password", "Error", JOptionPane.ERROR_MESSAGE);
	    return;
	}
	
	String newPassword = JOptionPane.showInputDialog(this, "Please enter your new password");
	
	if (newPassword == null) {
		return;
	}

	if (newPassword.equals("")) {
	    JOptionPane.showMessageDialog(this, "Please enter a password", "Error", JOptionPane.ERROR_MESSAGE);
	    return;
	}
	
	if (newPassword.length() < 8){
	     JOptionPane.showMessageDialog(this, "Your new password must be atleast 8 characters long.", "Error", JOptionPane.ERROR_MESSAGE);
	    return;
	}

	try {
	    APIUtils.changePassword(ApplicationContext.getToken(), oldPassword, newPassword);

	} catch (NullPointerException | WebClientRequestException ex) {

	    JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

	} catch (WebClientResponseException ex) {

	    JsonObject body = (JsonObject) JsonParser.parseString(ex.getResponseBodyAsString());

	    if (body == null) {
		JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		return;
	    }
	    if (body.has("Status")) {
		String status = body.getAsJsonPrimitive("Status").getAsString();
		JOptionPane.showMessageDialog(this, status, "Error", JOptionPane.ERROR_MESSAGE);
	    } else {
		JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

	    }

	}

    }//GEN-LAST:event_btnChangePasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnChangeUsername;
    private javax.swing.JButton btnDeleteAccount;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblHighScore;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
