/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package henry.savaryjackson.javatetris.GUI;

/**
 *
 * @author hsavaryjackson
 */
public class Screen extends javax.swing.JFrame {
    boolean paused ;
    
    private TetrisScreen screen;
    private TetrisGrid grid; 
    
    /**
     * Creates new form Screen
     */
    public Screen() {
	initComponents();
	grid = new TetrisGrid(6,6);
	screen = new TetrisScreen(10,24, grid, this);
	updateUI();
	add(screen);
	add(grid);
	grid.setLocation(600, 100);
	screen.requestFocus();
	setDefaultCloseOperation(EXIT_ON_CLOSE);
	setSize(900,800);
	setVisible(true);
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUI = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        lblPreviewGrid = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLines = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnStop.setText("Quit");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        lblPreviewGrid.setText("Next Piece:");

        lblLevel.setText("Level:");

        lblScore.setText("Score:");

        lblLines.setText("Lines:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlUILayout = new javax.swing.GroupLayout(pnlUI);
        pnlUI.setLayout(pnlUILayout);
        pnlUILayout.setHorizontalGroup(
            pnlUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUILayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pnlUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStop)
                    .addComponent(btnPlay)
                    .addGroup(pnlUILayout.createSequentialGroup()
                        .addGroup(pnlUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPreviewGrid)
                            .addComponent(lblLevel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLines, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblScore, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        pnlUILayout.setVerticalGroup(
            pnlUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUILayout.createSequentialGroup()
                .addGroup(pnlUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUILayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblPreviewGrid)
                        .addGap(89, 89, 89)
                        .addComponent(lblLevel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLines)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblScore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUILayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)))
                .addComponent(btnPlay)
                .addGap(18, 18, 18)
                .addComponent(btnStop)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        getContentPane().add(pnlUI);
        pnlUI.setBounds(290, 10, 262, 417);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        //switch the whether the screen is paused
	screen.paused = !screen.paused;
	
	//if the game is paused, and the game has not yet started or is over
	if (!screen.inSession){
	    screen.initTiles();
	    screen.updateSurface(0, screen.w-1);
	    screen.createPiece();
	    screen.clock.start();
	    screen.inSession = true;
	    
	}
	if (!screen.paused)
	    btnStop.setText("Pause"); 
	
	screen.requestFocus();
	
    }//GEN-LAST:event_btnPlayActionPerformed

    public void updateUI(){
	lblScore.setText(String.format("Score: %d", screen.points));
	lblLines.setText(String.format("Lines: %d" , screen.linesCleared));
	if (screen.paused){
	    btnStop.setText("Quit");
	}
	repaint();
	
    }
    
    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed

	if (screen.paused){
	    dispose();
	    System.exit(0);
	}else {
	    btnStop.setText("Quit");
	    screen.paused = true;
	}
    }//GEN-LAST:event_btnStopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblLines;
    private javax.swing.JLabel lblPreviewGrid;
    private javax.swing.JLabel lblScore;
    private javax.swing.JPanel pnlUI;
    // End of variables declaration//GEN-END:variables
}
