/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package henry.savaryjackson.javatetris.GUI;

/**
 *
 * @author hsavaryjackson
 */
public class Screen extends javax.swing.JFrame {
    boolean paused ;
    /**
     * Creates new form Screen
     */
    public Screen() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblScore = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        lblPreviewGrid = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLines = new javax.swing.JLabel();
        tetrisGrid1 = new henry.savaryjackson.javatetris.GUI.TetrisGrid(5,6);
        tetrisScreen1 = new henry.savaryjackson.javatetris.GUI.TetrisScreen(10,24);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnStop.setText("Pause");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        lblPreviewGrid.setText("Next Piece:");

        lblLevel.setText("Level:");

        jLabel3.setText("Score:");

        lblLines.setText("Lines:");

        javax.swing.GroupLayout tetrisGrid1Layout = new javax.swing.GroupLayout(tetrisGrid1);
        tetrisGrid1.setLayout(tetrisGrid1Layout);
        tetrisGrid1Layout.setHorizontalGroup(
            tetrisGrid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tetrisGrid1Layout.setVerticalGroup(
            tetrisGrid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout lblScoreLayout = new javax.swing.GroupLayout(lblScore);
        lblScore.setLayout(lblScoreLayout);
        lblScoreLayout.setHorizontalGroup(
            lblScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblScoreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lblScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(lblScoreLayout.createSequentialGroup()
                        .addGroup(lblScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lblPreviewGrid)
                            .addComponent(btnStop)
                            .addComponent(btnPlay))
                        .addGap(70, 70, 70))
                    .addGroup(lblScoreLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLevel)
                        .addGap(107, 107, 107))))
            .addGroup(lblScoreLayout.createSequentialGroup()
                .addGroup(lblScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblScoreLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(lblLines))
                    .addGroup(lblScoreLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(tetrisGrid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        lblScoreLayout.setVerticalGroup(
            lblScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblScoreLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblPreviewGrid)
                .addGap(18, 18, 18)
                .addComponent(tetrisGrid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnPlay)
                .addGap(33, 33, 33)
                .addComponent(btnStop)
                .addGap(46, 46, 46)
                .addComponent(lblLevel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(61, 61, 61)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(lblLines)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tetrisScreen1Layout = new javax.swing.GroupLayout(tetrisScreen1);
        tetrisScreen1.setLayout(tetrisScreen1Layout);
        tetrisScreen1Layout.setHorizontalGroup(
            tetrisScreen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );
        tetrisScreen1Layout.setVerticalGroup(
            tetrisScreen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tetrisScreen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tetrisScreen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
	paused = !paused;
	if (paused)
	    btnStop.setText("Pause"); 
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed

	if (paused){
	    dispose();
	}else {
	    btnStop.setText("Quit");
	    paused = true;
	}
    }//GEN-LAST:event_btnStopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblLines;
    private javax.swing.JLabel lblPreviewGrid;
    private javax.swing.JPanel lblScore;
    private henry.savaryjackson.javatetris.GUI.TetrisGrid tetrisGrid1;
    private henry.savaryjackson.javatetris.GUI.TetrisScreen tetrisScreen1;
    // End of variables declaration//GEN-END:variables
}
