/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package henry.savaryjackson.javatetris.GUI;

/**
 *
 * @author hsavaryjackson
 */
public class Screen extends javax.swing.JFrame {
    boolean paused ;
    
    /**
     * Creates new form Screen
     */
    public Screen() {
	initComponents();
	invalidate();
	updateUI();
	screen.requestFocus();
	setDefaultCloseOperation(EXIT_ON_CLOSE);
	setSize(900,800);
	setVisible(true);
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUI = new javax.swing.JPanel();
        btnStop = new javax.swing.JButton();
        lblLevel = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLines = new javax.swing.JLabel();
        lblNextPiece = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tetris");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlUI.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnStop.setFont(new java.awt.Font("Futura", 1, 14)); // NOI18N
        btnStop.setText("Quit");
        btnStop.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        lblLevel.setFont(new java.awt.Font("Futura", 1, 14)); // NOI18N
        lblLevel.setText("Level:");

        lblScore.setFont(new java.awt.Font("Futura", 1, 14)); // NOI18N
        lblScore.setText("Score:");

        lblLines.setFont(new java.awt.Font("Futura", 1, 14)); // NOI18N
        lblLines.setText("Lines:");

        lblNextPiece.setFont(new java.awt.Font("Futura", 1, 14)); // NOI18N
        lblNextPiece.setText("Next Piece:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );

        btnPlay.setFont(new java.awt.Font("Futura", 1, 14)); // NOI18N
        btnPlay.setText("Play");
        btnPlay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUILayout = new javax.swing.GroupLayout(pnlUI);
        pnlUI.setLayout(pnlUILayout);
        pnlUILayout.setHorizontalGroup(
            pnlUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUILayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPlay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStop)
                .addGap(0, 0, 0)
                .addComponent(lblLevel)
                .addGap(0, 0, 0)
                .addComponent(lblScore)
                .addComponent(lblLines)
                .addComponent(lblNextPiece)
                .addGap(68, 68, 68))
            .addGroup(pnlUILayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel4)
                .addGap(643, 748, Short.MAX_VALUE))
        );
        pnlUILayout.setVerticalGroup(
            pnlUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUILayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addGroup(pnlUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUILayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(pnlUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnStop)
                                .addComponent(btnPlay))
                            .addGroup(pnlUILayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(pnlUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLevel)
                                    .addComponent(lblScore)
                                    .addComponent(lblLines)
                                    .addComponent(lblNextPiece)))))
                    .addGroup(pnlUILayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        getContentPane().add(pnlUI, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        //switch the whether the screen is paused
	screen.paused = !screen.paused;
	
	//if the game is paused, and the game has not yet started or is over
	if (!screen.inSession){
	    screen.initTiles();
	    screen.updateSurface(0, screen.w-1);
	    screen.createPiece();
	    screen.clock.start();
	    screen.inSession = true;
	    
	}
	if (!screen.paused)
	    btnStop.setText("Pause"); 
	
	screen.requestFocus();
	
    }//GEN-LAST:event_btnPlayActionPerformed

    public void updateUI(){
	lblScore.setText(String.format("Score: %d", screen.points));
	lblLines.setText(String.format("Lines: %d" , screen.linesCleared));
	if (screen.paused){
	    btnStop.setText("Quit");
	}
	repaint();
	
    }
    
    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed

	if (screen.paused){
	    dispose();
	    System.exit(0);
	}else {
	    btnStop.setText("Quit");
	    screen.paused = true;
	}
    }//GEN-LAST:event_btnStopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblLines;
    private javax.swing.JLabel lblNextPiece;
    private javax.swing.JLabel lblScore;
    private javax.swing.JPanel pnlUI;
    // End of variables declaration//GEN-END:variables
}
