/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package henry.savaryjackson.javatetris.GUI;

import henry.savaryjackson.javatetris.utils.Piece;
import java.awt.Color;
import java.awt.Graphics;
import java.util.HashMap;

/**
 *
 * @author hsavaryjackson
 */
public class TetrisGrid extends javax.swing.JPanel {

    /** Creates new form TetrisGrid */
    int w,h;
    byte[][] grid;
    
    HashMap<Piece.tetrominoes, Color> colourTable;
    public TetrisGrid(int w , int h) {
	grid = new byte[h][w];
        initComponents();
	initializeColourTable();

    }
    
    @Override
    public void paint(Graphics g){
	super.paint(g);
    }
    
    private void initializeColourTable(){
	colourTable = new HashMap<>();
	colourTable.put(Piece.tetrominoes.I, Color.CYAN);
	colourTable.put(Piece.tetrominoes.J, Color.BLUE);
	colourTable.put(Piece.tetrominoes.L, Color.ORANGE);
	colourTable.put(Piece.tetrominoes.O, Color.YELLOW);
	colourTable.put(Piece.tetrominoes.S, Color.GREEN);
	colourTable.put(Piece.tetrominoes.T, Color.PINK);
	colourTable.put(Piece.tetrominoes.Z, Color.RED);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
